// my-app/src/components/ColaboradorCard.svelte
<script>
	import { query } from 'svelte-apollo';
	import DeleteButton from "./DeleteButton.svelte";
	import { GET_COLABORADOR } from '../queries/colaboradoresQuery';

	export let dni

	const colaborador = query(GET_COLABORADOR,
	{ variables: {dniCifColaborador: dni} });
</script>

{#if $colaborador.loading}
	<p>Loading...</p>
{:else if $colaborador.error}
	<p>Oh no... {$colaborador.error.message}</p>
{:else}
	<div class="card">
		<a class="btn" href="colaboradores/{$colaborador.data.colaborador.dniCifColaborador}">
			{$colaborador.data.colaborador.nombreColaborador}
		</a>
		<DeleteButton on:clicked />
	</div>
{/if}

<style>
	.card {
		display: flex;
		align-items: center;
		justify-content: space-between;
		box-shadow:
			rgba(0, 0, 0, 0.02) 0px 1px 3px 0px,
			rgba(27, 31, 35, 0.15) 0px 0px 0px 1px;
		height: 100px;
		margin: 10px 0;
		vertical-align: middle;
		padding: 10px 30px;
		text-transform: capitalize;
		border-radius: 10px;
	}
</style>

// frontend/src/components/ColaboradorCard.vue
<script setup>
import DeleteColaboradorButton from './DeleteColaboradorButton.vue'
import UpdateColaboradorButton from './UpdateColaboradorButton.vue'
import { defineEmits } from 'vue';
import { useQuery } from '@vue/apollo-composable'
import { GET_COLABORADOR } from '../graphql/Queries/Colaboradores.js'

const props = defineProps({
  dni: {
    type: String,
    required: true
  }
})
const { result, loading, error } = useQuery(
  GET_COLABORADOR,
  { dniCifColaborador: props.dni }
)

const emits = defineEmits(
  ['delete']
)
const handleCkick = () => {
  emits('delete')
}

</script>

<template>
  <div v-if="loading" class="loading">Loading...</div>
  <div v-if="error" class="error">Oh no... {{ error }}</div>
  <div v-if="result && result.colaborador" class="colaboradorCard">
    <div>
      <p class="nombre">
        {{ result.colaborador.nombreColaborador }} {{ result.colaborador.apellidosColaborador }}
      </p>
      <p style="color: #9aa0a6" id="dni">{{ result.colaborador.dniCifColaborador }}</p>
    </div>
    <div>
      <UpdateColaboradorButton :dniCifColaborador="result.colaborador.dniCifColaborador" />
      <DeleteColaboradorButton :dniCifColaborador="result.colaborador.dniCifColaborador" @delete="handleCkick" />
    </div>
  </div>
</template>

<style>
.colaboradorCard {
  border: 1px solid rgba(0, 0, 0, 0.2);
  border-radius: 15px;
  padding: 10px;
  margin: 10px 0;
  display: flex;
  justify-content: space-between;
  align-items: center;
  box-shadow: rgba(0, 0, 0, 0.05) 0px 10px 15px -3px;
}

button {
  background-color: white;
  border-radius: 8px;
  padding: 10px;
  transition: 0.3s ease;
  cursor: pointer;
}
</style>
